FROM python:3.11-slim

WORKDIR /app


COPY api.py .
COPY core.py .

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt \
    && apt-get update && apt-get install -y curl

CMD ["uvicorn", "api:app", "--host", "0.0.0.0", "--port", "8000"]